### ISSUE TITLE
ModuleNotFoundError: No module named 'feat.pyfeat'

### ISSUE THREAD

**Issue by hengzhe-zhang** [cavalab/feat#288]
Thanks for providing such an excellent package. I tried to install this package, but I have encountered the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhangheng1/feat-0.5.1/feat/__init__.py", line 1, in <module>
    from .feat import Feat, FeatRegressor, FeatClassifier
  File "/home/zhangheng1/feat-0.5.1/feat/feat.py", line 12, in <module>
    from .pyfeat import PyFeat
ModuleNotFoundError: No module named 'feat.pyfeat'
```
Could you help me with this problem? Thanks!

**Comment by hengzhe-zhang** [comment]
I have solved this problem. It seems that this problem is caused by running the python in the installation folder. Simply exiting the installation folder is able to solve this problem.
